
  const languages  = {
    "tr": {
        "enter_username": "Kullanıcı adınızı girin.",
        "info_deleted": "Bilgileriniz silindi.",
        "user_name": "Kullanıcı Adı:",
        "sign_as": "Şu şekilde giriş yap:",
        "online": "Çevrimiçi (Varsayılan)",
        "busy": "Meşgul",
        "away": "Uzakta",
        "remember_me": "Beni hatırla",
        "sign_auto": "Otomatik olarak giriş yap",
        "sign_in": "Giriş yap",
        "unable_connect_server": "Sunucuya bağlanılamıyor, daha sonra tekrar deneyin!",
        "signing_in": "Giriş yapılıyor...",
        "cancel": "İptal",
        "cant_update_from_keyboard": "Bu sayfayı klavye ile güncellemek mümkün değildir.",
        "online_users_appear": "* Çevrimiçi kullanıcılar bu listede görünecektir.",
        "busy_p": "(Meşgul)",
        "away_p": "(Uzakta)",
        "click_to_spotify": "Şu anda dinlediğiniz şarkıyı <br /> Spotify'da eklemek için tıklayın.",
        "connect": "Bağlan",
        "insert_subnick": "Alt takma adınızı buraya girin",
        "somebody": "Birisi",
        "has_just_signed": "az önce giriş yaptı.",
        "your_avatar": "Avatarınız",
        "select_your_avatar": "Avatarınızı seçin",
        "how_you_want_appear": "Messenger'da nasıl görünmek istediğinizi seçin.",
        "custom_images": "Kendi resmimi eklemek istiyorum",
        "default_images": "Varsayılan Resimler",
        "close": "Kapat",
        "you_p": "(Sen)",
        "select_image_below": "Kesip kaydetmek için aşağıdaki bir resim seçin.",
        "save": "Kaydet",
        "stop": "Dur",
        "send": "Gönder"
    },
    "en": {
        "enter_username": "You must enter your username.",
        "info_deleted": "Information deleted.",
        "user_name": "Username:",
        "sign_as": "Sign in as:",
        "online": "Online (Default)",
        "busy": "Busy",
        "away": "Away",
        "remember_me": "Remember-me",
        "sign_auto": "Sign me in automatically",
        "sign_in": "Sign in",
        "unable_connect_server": "Unable to connect to the server, try again!",
        "signing_in": "Signing in...",
        "cancel": "Cancel",
        "cant_update_from_keyboard": "It is not possible to update this page from the keyboard.",
        "online_users_appear": "* Online users will appear in this list.",
        "busy_p": "(Busy)",
        "away_p": "(Away)",
        "click_to_spotify": "Click to insert the song <br /> you are listening to now on spotify.",
        "connect": "Connect",
        "insert_subnick": "Insert your subnick here",
        "somebody": "Somebody",
        "has_just_signed": "has just signed in.",
        "your_avatar": "Your Avatar",
        "select_your_avatar": "Select your avatar",
        "how_you_want_appear": "Choose how you want to appear in Messenger.",
        "custom_images": "Custom Images",
        "default_images": "Default Images",
        "close": "Close",
        "you_p": "(You)",
        "select_image_below": "Select a image below to cut and save.",
        "save": "Save",
        "stop": "Stop",
        "send": "Send"
    },
    "br": {
        "enter_username": "Você deve colocar o seu nome de usuário.",
        "info_deleted": "Informações limpas",
        "user_name": "Nome de usuario:",
        "sign_as": "Entrar como:",
        "online": "Online (Padrão)",
        "busy": "Ocupado",
        "away": "Ausente",
        "remember_me": "Lembrar-me",
        "sign_auto": "Entrar Automaticamente",
        "sign_in": "Entrar",
        "unable_connect_server": "Não foi possivel conectar ao servidor, tente novamente!",
        "signing_in": "Entrando...",
        "cancel": "Cancelar",
        "cant_update_from_keyboard": "Não é possivel atualizar essa pagina pelo teclado.",
        "online_users_appear": "* Usuários onlines aparecerão nesta lista.",
        "busy_p": "(Ocupado)",
        "away_p": "(Ausente)",
        "click_to_spotify": "Clique para inserir a musica<br /> que está ouvindo agora no spotify.",
        "connect": "Conectar",
        "insert_subnick": "Insira seu subnick aqui",
        "somebody": "Alguém",
        "has_just_signed": "acabou de entrar.",
        "your_avatar": "Imagem para Exibição",
        "select_your_avatar": "Selecione uma Imagem para exibição",
        "how_you_want_appear": "Escolha como você deseja aparecer no Messenger.",
        "custom_images": "Imagens custom",
        "default_images": "Imagens comuns",
        "close": "Fechar",
        "you_p": "(você)",
        "select_image_below": "Selecione um arquivo abaixo para fazer o recorte e salvar.",
        "save": "Salvar",
        "stop": "Parar",
        "send": "Enviar"
    }
}

export default languages;

